# This is a Visual Studio extension installation task for Dev Box.

name: install-vs-extension
description: Installs a Visual Studio extension
author: Microsoft Corporation
command: ".\\Install-VSIXExtension.ps1 -MarketplaceItemName {{marketplaceItemName}}"
inputs:
  marketplaceItemName:
    type: string
    required: true
    description: |
      The name of the Visual Studio extension to install.
      For example, "GitHub.copilotvs".
      Visit https://marketplace.visualstudio.com to learn
      more about Visual Studio extensions.
