# This is a simple powershell command execution task for Dev Box.

name: powershell
description: Execute a powershell command
author: Microsoft Corporation
command: ".\\runcommand.ps1 -command {{command}} -workingDirectory {{workingDirectory}}"
inputs:
  command:
    type: string
    defaultValue: ""
    required: true
    description: The command to execute
  workingDirectory:
    type: string
    defaultValue: ""
    required: false
    description: The working directory to execute the command in
