name: LinkedTemplate
summary: This is testing linked Bicep modules in the Bicep runner
description: Deploys a linked template for an app-configuration and a storage account
templatePath: main.bicep
parameters:
- id: "appConfigName"
  name: "App Config Name"
  description: "Name of the App Config"
  type: "string"
  required: true
- id: "storageAccountName"
  name: "Storage Account Name"
  description: "Name of the Storage Account"
  type: "string"
  required: true
- id: "location"
  name: "location"
  description: "Location to deploy the environment resources"
  default: "eastus"
  type: "string"
runner: Bicep
