# This is a Chocolatey package installation task for Dev Box.

name: choco
description: Installs a Chocolatey package.
author: Microsoft Corporation
command: "./Choco.ps1 -Package {{package}} -Version {{version}} -IgnoreChecksums {{ignoreChecksums}}"
inputs:
  package:
    defaultValue: ""
    type: string
    required: true
    description: |
      The name of the Chocolatey package to install.
      For example, "git".
      Visit https://chocolatey.org/packages to learn
      more about Chocolatey packages. 
  version:
    defaultValue: ""
    type: string
    required: false
    description: The version of the Chocolatey package to install.
  ignoreChecksums:
    defaultValue: false
    type: boolean
    required: false
    description: Whether to ignore checksums when installing the package.
documentation:
  notes: This task is used to install a Chocolatey package.
  examples:
    - task: choco
      description: install OracleJDK 17.0.2
      inputs:
        package: oraclejdk
        version: 17.0.2
    - task: choco
      description: install notepad++
      inputs:
        package: notepadplusplus
