
# This is a Chocolatey package installation task for Dev Box.
$schema: "1.0"
name: choco
description: Installs a Chocolatey package.
author: Microsoft Corporation
command: "./Choco.ps1 -Package {{package}} -Version {{version}} -Switches {{switches}} -IgnoreChecksums {{ignoreChecksums}}"
parameters:
  package:
    default: ""
    type: string
    required: true
    description: |
      The name of the Chocolatey package to install.
      For example, "git".
      Visit https://chocolatey.org/packages to learn
      more about Chocolatey packages. 
  version:
    default: ""
    type: string
    required: false
    description: The version of the Chocolatey package to install.
  switches:
    default: ""
    type: string
    required: false
    description: Additional params required for the package to install.  
  ignoreChecksums:
    default: false
    type: boolean
    required: false
    description: Whether to ignore checksums when installing the package.
documentation:
  notes: This task is used to install a Chocolatey package.
  examples:
    - name: choco
      description: install OracleJDK 17.0.2
      parameters:
        package: oraclejdk
        version: 17.0.2
    - name: choco
      description: install azure functions core tools 
      parameters:
        package: azure-functions-core-tools
        switches: /x64
    - name: choco
      description: install notepad++
      parameters:
        package: notepadplusplus
